# Depends upon: Makefile.library, Makefile.compiler

PositiveTargetDir := $(TargetDir)/tests/positive
PositiveInterDir := $(PositiveTargetDir).inter
PositiveWarnDir := $(PositiveTargetDir).warn
PositiveOutDir := $(PositiveTargetDir).out
PositiveErrDir := $(PositiveTargetDir).err
PositiveSrcDir := compiler/tests/positive
PositiveSrcPaths := $(wildcard $(PositiveSrcDir)/*.ktn)
PositiveSrcNames := $(basename $(notdir $(PositiveSrcPaths)))
PositiveTargetPaths := $(addprefix $(PositiveTargetDir)/, $(PositiveSrcNames))
# NegSrcPaths := $(wildcard $(PositiveSrcDir)/negative/*.ktn)

ifdef DEBUG
  PositiveDebugFlags := -DDEBUG -g
else
  PositiveDebugFlags :=
endif

.PHONY : clean-tests
clean-tests :
	@ echo 'Cleaning test build files ...'
	@ rm -rf $(PositiveTargetDir)/* \
		$(PositiveInterDir)/* \
		$(PositiveOutDir)/* \
		$(PositiveErrDir)/* \
		$(PositiveWarnDir)/*

.PHONY : tests
tests : $(PositiveTargetPaths)
	@ mkdir -p $(PositiveOutDir)
	@ mkdir -p $(PositiveWarnDir)
	@ mkdir -p $(PositiveErrDir)
	@ echo 'Running tests ...'
	@ ./run-tests.sh $(PositiveSrcDir) $(PositiveTargetDir)

$(PositiveInterDir)/%.c : $(PositiveSrcDir)/%.ktn $(CompTargetPath)
	$(call ensure_buildable,$@)
	@ mkdir -p $(PositiveWarnDir)
	@ $(CompTargetPath) $< > $@ \
		2> $(PositiveWarnDir)/$(basename $(notdir $@))

$(PositiveTargetDir)/% : $(PositiveInterDir)/%.c $(LibTargetPath)
	$(call ensure_buildable,$@)
	@ echo 'Building test $(notdir $@) ...'
	@ $(CC) -std=c99 $< \
		-L$(TargetDir) -l$(LibTargetName) -lm -Ilibrary -o $@ \
		$(PositiveDebugFlags)
