CompSrcDir := compiler
CompSrcPaths := $(wildcard $(CompSrcDir)/*.hs)
CompTargetFile := kitten
CompTargetPath := $(TargetDir)/build/kitten/$(CompTargetFile)

.PHONY : clean-compiler
clean-compiler :
	@ echo 'Cleaning compiler build files ...'
	@ $(CABAL) clean --builddir=$(TargetDir) -v0

.PHONY : compiler
compiler : $(CompTargetPath)

$(CompTargetPath) : $(CompSrcPaths)
	$(CABAL) build --builddir=$(TargetDir)
